baseurl = "https://inonedamnpage.github.io/"
title = "In One Damn Page"
languageCode = "en-us"
paginate = 10
theme = "Hugo-Octopress"
canonifyurls = true

[indexes]
	tag = "tags"
	category = "categories"

[params]
	# If false, all of the post will appear on front page (and in pagination)
	truncate = true

	# Author's name (this will appear in metadata and under posts)
	author = "Saurav Modak"

	# This text appears in the site header under website title
	subtitle = "Personal Notes While Learning"

	# Google analytics code
	# googleAnalytics = "google analytics"

	# Disqus shortcode
	# Disable comments for a specific post by adding "comments: false" in its frontmatter
	# disqusShortname = "Your disqus shortname"

	rss = true  # switch to true to enable RSS icon link

	# Website's default description
	defaultDescription = "Saurav Modak's Learning Site"
	pygmentscodefences = true
